"""Generate requirements-deploy.txt from pyproject.toml.

The deployment image needs the same dependencies the project declares, and a
hand-written second copy of that list drifts. It already did: the first version
of the Dockerfile listed them by hand, missed opentelemetry - which nothing in
`risk` imports but `sim.observability` does at module scope - and the container
died on import after a clean build.

torch is excluded because the image installs the CPU-only build from PyTorch's
own index first; letting the resolver see it here fetches the CUDA wheel and
undoes that.

Run `make deploy-reqs` after changing dependencies.
"""
from __future__ import annotations

import sys
from pathlib import Path

try:
    import tomllib                      # Python 3.11+
except ModuleNotFoundError:             # pragma: no cover - older interpreters
    import tomli as tomllib

ROOT = Path(__file__).resolve().parents[1]

# Installed separately, from a different index.
EXCLUDED = {"torch"}


def package_name(spec: str) -> str:
    """The bare name, without extras or a version constraint."""
    for separator in ("[", ">", "<", "=", "!", "~", " "):
        spec = spec.split(separator)[0]
    return spec.strip().lower()


def main() -> None:
    manifest = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))
    dependencies = manifest["project"]["dependencies"]
    if len(dependencies) < 10:
        # A guard against parsing a truncated list. An earlier hand-rolled
        # parser split on the first "]" - which appeared inside a comment - and
        # silently produced four dependencies out of twenty-one.
        raise SystemExit(
            f"only {len(dependencies)} dependencies parsed; the manifest has "
            f"more than that, so this read is wrong")

    kept = [d for d in dependencies if package_name(d) not in EXCLUDED]
    dropped = [d for d in dependencies if package_name(d) in EXCLUDED]

    body = "\n".join([
        "# Generated by scripts/deploy_requirements.py - do not edit.",
        "# Regenerate with `make deploy-reqs` after changing pyproject.toml.",
        "#",
        "# torch is installed separately in the Dockerfile, from PyTorch's",
        "# CPU-only index. Listing it here would fetch the CUDA build.",
        *sorted(kept),
        "",
    ])

    out = ROOT / "requirements-deploy.txt"
    previous = out.read_text(encoding="utf-8") if out.exists() else ""
    out.write_text(body, encoding="utf-8")

    print(f"{len(kept)} dependencies written to {out.name}")
    if dropped:
        print(f"excluded (installed separately): {', '.join(dropped)}")
    if previous and previous != body:
        print("CHANGED - rebuild the image")
    # A non-zero exit when the file was stale, so CI can fail on a drifted copy
    # rather than deploying one.
    sys.exit(1 if (previous and previous != body) else 0)


main()
